// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqYB75i2YAPNRTY6Jkh2bzPxn05ittCLo',
    appId: '1:920523355148:web:e31c3cea5016ee9d072a29',
    messagingSenderId: '920523355148',
    projectId: 'crud-mahasiswa-49a25',
    authDomain: 'crud-mahasiswa-49a25.firebaseapp.com',
    storageBucket: 'crud-mahasiswa-49a25.firebasestorage.app',
    measurementId: 'G-Z4CDSZPX76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzukX5qIzZzyxvKYHn9ftq0eNfRwH4J-o',
    appId: '1:920523355148:android:11b2a14eef5c7f50072a29',
    messagingSenderId: '920523355148',
    projectId: 'crud-mahasiswa-49a25',
    storageBucket: 'crud-mahasiswa-49a25.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqYB75i2YAPNRTY6Jkh2bzPxn05ittCLo',
    appId: '1:920523355148:web:a241e5d5d56ee312072a29',
    messagingSenderId: '920523355148',
    projectId: 'crud-mahasiswa-49a25',
    authDomain: 'crud-mahasiswa-49a25.firebaseapp.com',
    storageBucket: 'crud-mahasiswa-49a25.firebasestorage.app',
    measurementId: 'G-56MJ7GJ058',
  );
}
